Milestone 5
AbigiyaTY/Blog_app pull request #5
Opened 2022-12-13 19:46 UTC by AbigiyaTY

In this milestone I:

- Write tests for controllers.

2022-12-13 23:26 UTC, prolajumokeoni reviewed
Hi @AbigiyaTY 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have all headers present in your readme, Make sure to add the section Future Features, including 1-3 potential features to be added,
kindly ensure all main headers from the [README template](https://github.com/microverseinc/readme-template/blob/master/README.md) are present 👍🏿 


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-13 23:35 UTC, prolajumokeoni reviewed
Hi @AbigiyaTY 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have all headers present in your readme, Make sure to add the section Future Features, including 1-3 potential features to be added,
kindly ensure all main headers from the [README template](https://github.com/microverseinc/readme-template/blob/master/README.md) are present 👍🏿 


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-14 00:33 UTC, mikethreels requested changes
Hi Abigail, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- linters are passing

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-14 00:33 UTC, mikethreels commented on spec/controllers/users_controller_spec.rb
> +    end
- [ ] your spec file should include tests that ensure the correct view template is rendered.
Example : `expect(response).to render_template(:show)`

2022-12-14 00:33 UTC, mikethreels commented on spec/controllers/users_controller_spec.rb
> +  end
- [ ] your spec file should include tests that ensure the correct view template is rendered.
Example : `expect(response).to render_template(:index)`

2022-12-14 00:33 UTC, mikethreels commented on spec/controllers/posts_controller_spec.rb
> +    end
- [ ] your spec file should include tests that ensure the correct view template is rendered.
Example : `expect(response).to render_template(:show)`

2022-12-14 00:33 UTC, mikethreels commented on spec/controllers/posts_controller_spec.rb
> +    end
- [ ] your spec file should include tests that ensure the correct view template is rendered.
Example : `expect(response).to render_template(:index)`

2022-12-14 01:01 UTC, Reem-lab approved these changes
# Hi @AbigiyaTY,👋🏻👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🚀🔥🎉🎉 
<img src="https://media2.giphy.com/media/G7lfJRrvdhtxK8OVGy/giphy.gif"/>

## Highlights ✨✨
- Followed Gitflow ✅
- Great working on the functionality 🔥🚀🎉
- Descriptive PR ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-14 01:11 UTC, merged